name: Astroseminars

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (daily | weekly | readme)"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests ics pytz

      - name: Run script
        run: |
          python update_schedule.py ${{ github.event.inputs.mode }}
